name: App Python para Testar Github Actions

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Instalando dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Teste com pytest
        run: |
          pytest
